### Login
### — 1) REGISTER USER (kalo user ngga milih role, otomatis jadi staff)
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "dedi musafir",
  "email": "dedi21@gmail.com",
  "password": "123456",
  "confpassword": "123456",
  "role": "manager" 
}

### — 2) LOGIN (dapat accessToken & refreshToken cookie)
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "fajar.manager@gmail.com",
  "password": "admin123"
}

### — 3) REFRESH TOKEN (ambil accessToken baru)
GET http://localhost:5000/token

### — 4) LOGOUT
DELETE http://localhost:5000/logout

### — 5) GET ALL USERS (hanya user yang sudah login)
GET http://localhost:5000/users
Authorization: Bearer 
### — 6) GET ME (ambil data user yang sedang login)
GET http://localhost:5000/me
Authorization: Bearer

### CRUD
### — 1) GET ALL PRODUCTS (login required)
GET http://localhost:5000/products
Authorization: Bearer 

### — 2) GET PRODUCT BY ID
GET http://localhost:5000/products/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJuYW1lIjoiZmFqYXIiLCJlbWFpbCI6ImZhamFyLm1hbmFnZXJAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDc2NzI5ODYsImV4cCI6MTc0NzY3Mzg4Nn0.7j8EKWiUaIlNuJ7FbDjbZCA76vOYnaTnkzEd4x8H4Js

### — 3) CREATE PRODUCT (manager only)
POST http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJuYW1lIjoiZmFqYXIiLCJlbWFpbCI6ImZhamFyLm1hbmFnZXJAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDc2Njg5NzgsImV4cCI6MTc0NzY2OTg3OH0.IbehqRlJB0MNOOxQGFymtc40tJn_wc_LJJFV82fBees
Content-Type: application/json

{
  "name": "Bugatti divo",
  "model": "pur card",
  "price": 13000000,
  "imageName": "divo.jpg",
  "description": "Mahakarya kecepatan absolut.",
  "stock": 5
}

### — 4) UPDATE PRODUCT (manager only)
PATCH  http://localhost:5000/products/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJuYW1lIjoiZmFqYXIiLCJlbWFpbCI6ImZhamFyLm1hbmFnZXJAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDc2NzI5ODYsImV4cCI6MTc0NzY3Mzg4Nn0.7j8EKWiUaIlNuJ7FbDjbZCA76vOYnaTnkzEd4x8H4Js
Content-Type: application/json

{
  "name": "Bugatti Bolide",
  "model": "luxury Sport",
  "price": 3250000,
  "imageName": "bolide.jpg",
  "description": "Versi terbaru dengan performa ditingkatkan.",
  "stock": 3
}

### — 5) DELETE PRODUCT (manager only)
DELETE http://localhost:5000/products/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJuYW1lIjoiZmFqYXIiLCJlbWFpbCI6ImZhamFyLm1hbmFnZXJAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDc2NzI5ODYsImV4cCI6MTc0NzY3Mzg4Nn0.7j8EKWiUaIlNuJ7FbDjbZCA76vOYnaTnkzEd4x8H4Js