### — 1) REGISTER USER (kalo user ngga milih role, otomatis jadi staff)
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "dedi musafir",
  "email": "dedi21@gmail.com",
  "password": "123456",
  "confpassword": "123456",
  "role": "manager"
}

### — 2) LOGIN (dapat accessToken & refreshToken cookie)
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "dedi21@gmail.com",
  "password": "123456"
}

### — 3) REFRESH TOKEN (ambil accessToken baru)
GET http://localhost:5000/token

### — 4) LOGOUT
DELETE http://localhost:5000/logout

### — 5) GET ALL USERS (hanya user yang sudah login)
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJuYW1lIjoiamFqYW5nIiwiZW1haWwiOiJqYWphbmdAZ21haWwuY29tIiwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzQ2MzczNzk2LCJleHAiOjE3NDYzNzM4NDF9.KKGA4D7vbNb7bw-e1EYR1X-jgty8vurvROtTtBlOSEk
### — 6) GET ALL PRODUCTS (login required)
GET http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJuYW1lIjoiamFqYW5nIiwiZW1haWwiOiJqYWphbmdAZ21haWwuY29tIiwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzQ2MzczNzk2LCJleHAiOjE3NDYzNzM4NDF9.KKGA4D7vbNb7bw-e1EYR1X-jgty8vurvROtTtBlOSEk

### — 7) GET PRODUCT BY ID
GET http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJuYW1lIjoicm9obWFuIiwiZW1haWwiOiJyb2htYW5AZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDYzNzM1NjksImV4cCI6MTc0NjM3NzE2OX0.RtlaBqhRZV6QtZxkdZAREDo41Cmj-mNgDlMvZeqORSI

### — 8) CREATE PRODUCT (manager only)
POST http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2LCJuYW1lIjoiZGVkaSBtdXNhZmlyIiwiZW1haWwiOiJkZWRpMjFAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDYzNzM5OTYsImV4cCI6MTc0NjM3NDA0MX0.N2DsVOJQ3RJWJn2XzEK5-aZGqOOF5Xzg_9OtNEitp_g
Content-Type: application/json

{
  "name": "Bugatti Chiron",
  "model": "spotify mantap Sport",
  "price": 3000000,
  "imageUrl": "https://link.to/bugatti.jpg",
  "description": "Mahakarya kecepatan absolut.",
  "stock": 5
}

### — 9) UPDATE PRODUCT (manager only)
PATCH  http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJuYW1lIjoicm9obWFuIiwiZW1haWwiOiJyb2htYW5AZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDYzNzM1NjksImV4cCI6MTc0NjM3NzE2OX0.RtlaBqhRZV6QtZxkdZAREDo41Cmj-mNgDlMvZeqORSI
Content-Type: application/json

{
  "name": "Bugatti Chiron",
  "model": "Pur Sport",
  "price": 3200000,
  "imageUrl": "https://link.to/bugatti-new.jpg",
  "description": "Versi terbaru dengan performa ditingkatkan.",
  "stock": 3
}

### — 10) DELETE PRODUCT (manager only)
DELETE http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2LCJuYW1lIjoiZGVkaSBtdXNhZmlyIiwiZW1haWwiOiJkZWRpMjFAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3NDYzNzM5OTYsImV4cCI6MTc0NjM3NDA0MX0.N2DsVOJQ3RJWJn2XzEK5-aZGqOOF5Xzg_9OtNEitp_g
